### ISSUE TITLE
Define controller as service 

### ISSUE THREAD

**Issue by houssrad** [winzou/StateMachineBundle#14]
I have method "UpdateStateToPaymentProgress" inside controller 

```
public function UpdateStateToPaymentProgress(Cart $cart, $state)
    {
        $dm = $this->getDocumentManager();
        $cart->setState($state);
        $dm->persist($cart);
        $dm->flush();
    }
```
This is my config file 

```
(...)
transitions:
            create:
                from: [new]
                to: created
            payment:
                from: [created]
                to:   progressPayment
(...)
callbacks:
            # will be called after applying a transition            
            after:
                progress_pay_cart:
                    on:   'payment'
                    do:   [@application.cart.checkout, 'UpdateStateToPaymentProgress']
                    args: ['object', '"progressPayment"']
```

i define controller as service in service.yml 

```
services:
    application.cart.checkout:
        class:     Application\CartBundle\Controller\CheckoutController 
```

the problem is when i call method $cartSM->apply('payment') , the entity dont change state, and the bundle dnt call method of controller.
