### ISSUE TITLE
Integer constants states

### ISSUE THREAD

**Issue by umpirsky** [winzou/StateMachineBundle#19]
Is it possible to use integer constants as states?

For example:

```php
<?php

namespace My\Bundle\Entity;

class Article
{
    const STATE_NEW = 1;
    const STATE_PENDING_REVIEW = 2;
    const STATE_AWAITING_CHANGES = 3;
    // ...
}
```

```yml
winzou_state_machine:
    my_bundle_article:
        class: My\Bundle\Entity\Article
        property_path: state           
        graph: simple                  
        states:
            - My\Bundle\Entity\Article::STATE_NEW # ?
            - My\Bundle\Entity\Article::STATE_PENDING_REVIEW # ?
            - My\Bundle\Entity\Article::STATE_AWAITING_CHANGES # ?
            # ...
```
