### ISSUE TITLE
support request - help.what does @sm.callback.cascade_transition do?

### ISSUE THREAD

**Issue by Mr-Negative** [winzou/StateMachineBundle#23]
I use sylius.
```
winzou_state_machine:
    sylius_order_checkout:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            addressed: ~
            shipping_selected: ~
            payment_selected: ~
            completed: ~
        transitions:
            address:
                from: [cart]
                to: addressed
            readdress:
                from: [payment_selected, shipping_selected, addressed]
                to: cart
            select_shipping:
                from: [addressed]
                to: shipping_selected
            reselect_shipping:
                from: [payment_selected, shipping_selected]
                to: addressed
            select_payment:
                from: [shipping_selected]
                to: payment_selected
            reselect_payment:
                from: [payment_selected]
                to: shipping_selected
            complete:
                from: [payment_selected]
                to: completed
        callbacks:
            after:
                sylius_process_cart:
                    on: ["address", "select_shipping"]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
                sylius_recalculate_cart:
                    on: ["address", "readdress", "select_shipping", "reselect_shipping", "select_payment", "reselect_payment"]
                    do: ["@sylius.order_processing.order_recalculator", "recalculate"]
                    args: ["object"]
                sylius_create_order:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'create'", "'sylius_order'"]
                sylius_create_payment:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object.getPayments()", "event", "'create'", "'sylius_payment'"]
                sylius_request_shipping:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'request_shipping'", "'sylius_order_shipping'"]

```

what is this @sm.callback.cascade_transition? i can't figure it out and its only one place in code
