### ISSUE TITLE
It's possibe to add several `do` in a callback? 

### ISSUE THREAD

**Issue by crevillo** [winzou/StateMachineBundle#30]
Hi there. Not an issue. Hope you don't mind i post the question here. I'm working with sylius and sylius used this bundle. In a sylius yml file you can see something like
```yml
winzou_state_machine:
    sylius_order_checkout:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        ...
        callbacks:
            after:               
                sylius_hold_inventory:
                    on: ["complete"]
                    do: ["@sylius.inventory.order_inventory_operator", "hold"]
                    args: ["object"]
```

My question is if i could add my own `do` to that `after sylius hold inventory` from my own bundle. I need that sylius still do its job, but  i need to do some things... is this possible?

**Comment by winzou** [comment]
Hi,

You just have to define another callback with the same `on` condition, and call you own callback. Sylius' one will still be called, and yours as well. Your callback will actually be totally independant from Sylius one.

Is that clear?

**Comment by crevillo** [comment]
do you mean something like
```yml
winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                myapp_hold_inventory:
                    on: ["complete"]
                    do: ["@myapp.inventory.order_inventory_operator", "hold"]
                    args: ["object"]
```
? thank you!.

**Comment by crevillo** [comment]
i think i got it, but i needed to a priority value to my new one callback. Does it make sense?
Thanks a lot.

**Comment by winzou** [comment]
Default priority is 0, you can tune it by adding the `priority` key:

```yaml
winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                myapp_hold_inventory:
                    on: ["complete"]
                    do: ["@myapp.inventory.order_inventory_operator", "hold"]
                    args: ["object"]
                    priority: 10
```
10 is greater than 0 so your callback will be called before Sylius one. Put a negative priority if you want to be called after.
