### ISSUE TITLE
Bug during overrides in configuration

### ISSUE THREAD

**Issue by xavren** [winzou/StateMachineBundle#32]
Hello,

I was trying the new sylius 1.0.0@alpha and tried to disable a state and transitions but it seems that the way that configuration is parsed does not respect overrides and merge all together...

I created test and made a PR, tell me if it seems ok for you and i can create the code to respect this spec

https://github.com/winzou/StateMachineBundle/pull/31

**Comment by winzou** [comment]
Hi,

To disable a state you can do the following:

```yaml
winzou_state_machine:
    an_extended_machine:
        states:
            a_state_to_disable: "::disabled"
```

Is this what you are looking for?

It's handled here: https://github.com/winzou/StateMachineBundle/blob/master/DependencyInjection/winzouStateMachineExtension.php#L69

**Comment by c-revillo** [comment]
Hello, i also experiencing this problem with sylius, now with the beta. i exposed my problem here https://github.com/Sylius/Sylius/issues/7095
There i've been told the solution to modify my appKernel.php a little bit and indeed it works. 

And as i said there, the other thing that worked was to put everything on app/config/config.yml and mofiy the Configuration for the State Machine Bundle a little bit. 

Tried the `::disabled` thing too, but no luck...

**Comment by winzou** [comment]
There are indeed different ways of merging symfony configuration. In your case you want to override all the states with your own array of states. But others will want to be able to just add one state, without being forced to rewrite the whole array of states. Both use cases cannot be handled at the same time :)

For your use case, you must use the `::disabled` trick, which should be working. Can you try again and if it is still not working, come back here with more details?

**Comment by c-revillo** [comment]
Sure, here's the thing. i'm trying to override the states that are defined in this sylius file https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml

As this means `SyliusCoreBundle` i added my own `app/Resources/SyliusCoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml`. 

There i copied everything and added the `::disabled` in one of the states like 
```yaml
winzou_state_machine:
    sylius_order_checkout:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            addressed: ~
            shipping_selected: '::disabled'
            payment_skipped: ~
            payment_selected: ~
            completed: ~
```

Now, if try debug the winzou_state_machine and look for that part i get...
`php bin/console debug:config winzou_state_machine` and i can see
```yaml
winzou_state_machine:
    sylius_order_checkout:
        class: Sylius\Component\Core\Model\Order
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: Sylius\Component\Resource\StateMachine\StateMachine
        states:
            cart: null
            addressed: null
            shipping_selected: '::disabled'
            payment_skipped: null
            payment_selected: null
            completed: null
```

The disabled is there... but my question is... should this means state has been really disabled? looking to the sylius documentation it looks like that state shouldn't appear in the output of the debug command at all... 
http://docs.sylius.org/en/latest/cookbook/checkout.html

Thanks, btw!

**Comment by winzou** [comment]
Can you try to execute this command `debug:winzou:state-machine`? Thanks

**Comment by c-revillo** [comment]
Ok, so, having the following in my `app/Resources/SyliusCoreBundle/config/app/state_machine/sylius_order_checkout.yml`

```yaml
winzou_state_machine:
    sylius_order_checkout:
        states:
            shipping_selected: '::disabled'
```

executing the command if prompts me what state machine i want to know about and selecting the `sylius_order_checkout` i get this
```
You have just selected: sylius_order_checkout
+--------------------+
| Configured States: |
+--------------------+
| cart               |
| addressed          |
| shipping_selected  |
| payment_skipped    |
| payment_selected   |
| completed          |
+--------------------+
+-----------------+-------------------+-------------------+
| Transition      | From(s)           | To                |
+-----------------+-------------------+-------------------+
| address         | cart              | addressed         |
|                 | addressed         |                   |
|                 | shipping_selected |                   |
|                 | payment_selected  |                   |
|                 | payment_skipped   |                   |
+-----------------+-------------------+-------------------+
| select_shipping | addressed         | shipping_selected |
|                 | shipping_selected |                   |
|                 | payment_selected  |                   |
|                 | payment_skipped   |                   |
+-----------------+-------------------+-------------------+
| skip_payment    | shipping_selected | payment_skipped   |
+-----------------+-------------------+-------------------+
| select_payment  | payment_selected  | payment_selected  |
|                 | shipping_selected |                   |
+-----------------+-------------------+-------------------+
| complete        | payment_selected  | completed         |
|                 | payment_skipped   |                   |
+-----------------+-------------------+-------------------+
```

Is this the expected behaviour? Thanks.
