### ISSUE TITLE
Execute a callback on multiple transitions

### ISSUE THREAD

**Issue by aguidis** [winzou/StateMachineBundle#33]
Hello,

I just would like to know if it's possible to execute the same callback on multiple transitions like :

```
        callbacks:
            after:
                create_invoice:
                    on:   ['confirm', 'cashing_and_collection_of_goods']
                    do:   [ "@app.infrastructure.state_handler.order.invoice", create ]
                    args: [ 'object' ]
```
