### ISSUE TITLE
Extra arguments when using callbacks

### ISSUE THREAD

**Issue by hookewin** [winzou/StateMachineBundle#41]
hi,
    i have a question on how to pass extra arguments when using callbacks, like i have the follow configuration:

```
callbacks:
    after:
         sylius_process_cart:
                    on: ["select_shipping", "address", "select_payment", "skip_shipping", "skip_payment"]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
```

then, in the args field i want to add another args(is an object), pls tell me how can i finish this operation? thx.
